### ISSUE TITLE
NC 20 Compatibility

### ISSUE THREAD

**Issue by toxpal** [TimoKunze/files_trackdownloads#15]
Are there any plans to make the app NC20 compatible? I'd like to upgrade, and this is the only app I use which doesn't support NC20 yet. It's very useful for me; therefore, I don't upgrade yet...

**Comment by TimoKunze** [comment]
I've released an update. Currently I cannot really test it. So please let me know whether it works.

**Comment by toxpal** [comment]
Thanks, will test this weekend.

**Comment by TimoKunze** [comment]
Did you find any issues?

**Comment by toxpal** [comment]
In fact, yes... After installing and enabling the app, its icon doesn't even appear in the top menu.

**Comment by Mathias-devop** [comment]
Hello,
I would like to ask you if there is something new about the compatibility with Nextcloud 20.
Regards.

**Comment by TimoKunze** [comment]
Well, I just enabled it on my instance of Nextcloud 20 and clicked the Activity icon in the top menu. The app is displayed just fine.

**Comment by toxpal** [comment]
Yes, I also re-enabled app and it works fine with NC 20. Maybe it was some issue with earliest v20.x release. Can confirm everything works fine now.
