### ISSUE TITLE
What is the difference to  Activities for shared file downloads  by Joas Schilling 

### ISSUE THREAD

**Issue by rubo77** [TimoKunze/files_trackdownloads#16]
The Readme should state the difference to the other App.

Can they be activated both at the same time? Is this a replacement? What is the benefit of this app to the other?

**Comment by TimoKunze** [comment]
I've updated the Readme. I guess both apps can be activated at the same time, but I don't think that this would be of any use.

**Comment by rubo77** [comment]
fixed with https://github.com/TimoKunze/files_trackdownloads/commit/5c47e914e9d49dc634d31ffd04747ad90aeedef5
