### ISSUE TITLE
Nextcloud 15 compatibitity

### ISSUE THREAD

**Issue by raydelgg** [TimoKunze/files_trackdownloads#5]
Nextcloud 15 has been released today. It would be nice if you could update this app to work on Nextcloud 15! Thank you!

**Comment by GoetheG** [comment]
This is a great app and I am really looking forward to the new version of it for Nextcloud 15 :) So you're right @raydelgg.

**Comment by gerroon** [comment]
Yeah, this is the only addon keeping me from moving to NC15

**Comment by GoetheG** [comment]
Me too, @gerroon :).

**Comment by Alwaysin** [comment]
Me too :D

**Comment by e-alfred** [comment]
@TimoKunze Can you create a new release for Nextcloud 15?

**Comment by TimoKunze** [comment]
Sorry, I have been on vacation for 1 month. I'm working on it now.

**Comment by TimoKunze** [comment]
@raydelgg @gerroon @GoetheG @Alwaysin @e-alfred Version 1.4.0 has been released and pushed to the store.
