### ISSUE TITLE
Activity not show in Nextcloud

### ISSUE THREAD

**Issue by feedbeg** [TimoKunze/files_trackdownloads#8]
Hello,

when i activate your app i get nothing new displayed in my nextcloud 17. Where can I see if someone has downloaded a file or where can I change settings?

With kind regards
Florian Strauß

**Comment by TimoKunze** [comment]
Hi,

The activity should be visible under /apps/activity/. The entries look like this:

> Shared file {file} was downloaded by {actor} via the browser

You also can see this information in a file's activity stream, e.g.:

> Downloaded by {actor} (via Browser)

If I'm not mistaken, downloads of guest users are not tracked. This has not been a use case for me and to be honest I wouldn't know how to implement it as I'm not very familar with the Nextcloud API.
So, could it be that the downloads you are missing have been done by guest users?

Best regards
Timo

**Comment by feedbeg** [comment]
Hello,

so the standard app activity must also be activated? 

With kind regards
Florian Strauß

**Comment by TimoKunze** [comment]
Yes.
